branch-defaults:
  master:
    environment: Backendudacityfoula-env
environment-defaults:
  Backendudacityfoula-env:
    branch: null
    repository: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: backend.udacity.foula
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: git
  workspace_type: Application
